### ISSUE TITLE
Having issues loading FBSDKCoreKit modules

### ISSUE THREAD

**Issue by joshbedo** [brentvatne/react-native-login#10]
I seem to be having an issue compiling the project, it always errors out on the FB SDK libraries. I already  installed the FB IOS SDK v4.0. I noticed within the xcode project the libraries were using the wrong path so i updated them with the path where i installed the SDK. After even doing that i'm still getting the same error so at this point i'm a little confused. I also noticed in the online version they name the directory `Frameworks` instead of `Libraries` i'm not familiar enough to know if that would be the problem. Here is what i'm seeing.

![](https://api.monosnap.com/rpc/file/download?id=Fple3TLMujWH62pU6saH2L2ehl4siN)
![](https://api.monosnap.com/rpc/file/download?id=w3AVdocleBHAgzvfxhWvuXDb90qGc7)
![](https://api.monosnap.com/rpc/file/download?id=1BEauoxmULmunLZMYqAzoesWfquDY9)

**Comment by brentvatne** [comment]
What do your search paths look like?

![screen shot 2015-04-21 at 3 53 34 pm](https://cloud.githubusercontent.com/assets/90494/7264257/9fc12f94-e83e-11e4-818e-a316cc43e8cf.png)

Maybe I should look at packaging the SDK within this project so it's not such a difficult setup..

**Comment by kmartinezmedia** [comment]
I also had this problem, and was unable to solve

**Comment by brentvatne** [comment]
@kmartinezmedia @joshbedo - OK I will look at packaging the Facebook SDK tomorrow and ping you both when it's done :smile:

**Comment by kmartinezmedia** [comment]
@brentvatne awesome thanks!

**Comment by kmartinezmedia** [comment]
I got it to work by copying folder 'Modules' in  FBSDKCoreKit.framework to the Bolts.framework. I then opened up the module.modulemap file in my text editor and replaced with this

framework module Bolts {
umbrella header "Bolts.h"

export *
module \* { export \* }

explicit module BFAppLinkResolver {
    header "BFAppLinkResolver.h"
    link "BFAppLinkResolver"
    export *
}}

Then saved and ran. Found solution here http://stackoverflow.com/questions/29435377/facebook-ios8-sdk-build-module-error-for-fbsdkcorekit

**Comment by joshbedo** [comment]
@kmartinezmedia I just tried what you mentioned above and that solved the build error woo! good find :dancer:

**Comment by brentvatne** [comment]
Looks like you solved it so I didn't prioritize integrating the SDK directly into the project today, perhaps on the weekend!

**Comment by joshbedo** [comment]
Sounds good, i might try sending over a PR :D

**Comment by ajrator** [comment]
I can't seem to find the Modules folder... Can someone help navigate?

**Comment by brentvatne** [comment]
This library is deprecated now in favour of https://github.com/facebook/react-native-fbsdk :)
