### ISSUE TITLE
FacebookLoginManager not initialized

### ISSUE THREAD

**Issue by ladas-larry** [brentvatne/react-native-login#12]
I have a trouble with require('NativeModules').FacebookLoginManager, though I did everything as it's sad in http://brentvatne.ca/facebook-login-with-react-native/. So FacebookLoginManager.newSession is not working.

![screen shot 2015-06-17 at 02 29 27](https://cloud.githubusercontent.com/assets/3543614/8197575/0f16fb62-149a-11e5-97b8-c166db812f56.png)

When I did a diff between my project and react-native-login I have found differences containing phrase 'FacebookLoginManager' in project.pbxproj. But when I pasted those lines into my project.pbxproj, it didn't worked either.

**Comment by brentvatne** [comment]
@Dharmoslap - the problem is that it hasn't been linked with the project I believe - perhaps I need to update the blog post to make that more clear.

It needs to show up under `Build Phases > Compile Sources`:

![](http://url.brentvatne.ca/1de1Z.png)

**Comment by brentvatne** [comment]
This library is deprecated now in favour of https://github.com/facebook/react-native-fbsdk :)
