### ISSUE TITLE
FBSDKAccessToken Properties

### ISSUE THREAD

**Issue by gilchenzion** [brentvatne/react-native-login#16]
Hey @brentvatne, really enjoying this react-native module. Any thought about including [other properties of the FBSDKAccessToken](https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAccessToken/)  in the response for the FacebookLoginManager? I am working on a project that needs the expiration date but it could be nice to include all the properties so that they are at least available for the developer. I'll put a PR together if it is something worth exploring.

**Comment by brentvatne** [comment]
@gilchenzion - glad you like it, I don't have any plans to add more functionality here because Facebook has released a much better library: https://github.com/facebook/react-native-fbsdk :) I'd recommend submitting a pull request on that if it doesn't work out for you!
