### ISSUE TITLE
Collecting User's Data

### ISSUE THREAD

**Issue by timdoes** [brentvatne/react-native-login#2]
Can you add an example of how to handle the users profile information?

**Comment by brentvatne** [comment]
@timdoes - sure. All that's necessary at this point is to use the Facebook JS SDK to grab the info put I'll put that in there along with an image of the user profile for an example when I get the chance today.

**Comment by brentvatne** [comment]
@timdoes - added this in a26e9a1ff9d3ab25fbfcab49ce8e9d2d93527b01
