### ISSUE TITLE
Npm install fails?

### ISSUE THREAD

**Issue by chadobado** [brentvatne/react-native-login#3]
Thanks for contributing this, great example of how to work with RCTBridgeModule.

I'm able to get everything working following along with your blog post.  

Unfortunately I'm not able to get the project in the repo working independently though.

```
git clone https://github.com/brentvatne/react-native-login.git
cd react-native-login
npm install
```

Fails with errors.  Tried various workarounds including using react-native's CLI to setup the project folder and manually linking files and libraries used.  Nothing got me all the way there, so I assume I'm going about this the wrong way.

Can you add some brief instructions on the readme?

Thanks

**Comment by brentvatne** [comment]
@chadobado - that's odd! Could you post the errors that you are seeing?

**Comment by chadobado** [comment]
Sorry for lagging on this.  Just cloned a fresh copy from your repo.

Npm install was successful this time around.  Only needed to add Bolts, FBSKCoreKit and FBSDKLoginKit to get things going.

Thanks!

**Comment by brentvatne** [comment]
Great, glad it worked out @chadobado!
