### ISSUE TITLE
"FBSDKCoreKit/FBSDKCoreKit.h file not found" - compiler error

### ISSUE THREAD

**Issue by voronianski** [brentvatne/react-native-login#4]
Very strange error.. I've just cloned this repo, ran `npm install` and opened via XCode and built it with `Cmd+R`.

Getting such error in `FacebookLoginManager.m` on `#import "FBSDKCoreKit/FBSDKCoreKit.h"` line though it looks like I have this framework in Libraries folder of XCode project. Any suggestions?

**Comment by brentvatne** [comment]
@voronianski - odd, try downloading the SDK from [here](https://developers.facebook.com/docs/ios) and let me know if that fixes your problem!

**Comment by voronianski** [comment]
@brentvatne thanks, that fixed the issue.

**Comment by brentvatne** [comment]
@voronianski - great, I'll add a comment to the README about that

**Comment by brunolemos** [comment]
If anyone comes here through Google, check [this answer](http://stackoverflow.com/a/42040832/2228575) on stackoverflow.
