### ISSUE TITLE
Already authorised triggers isCancelled

### ISSUE THREAD

**Issue by adriansdev** [brentvatne/react-native-login#5]
An app which is already authorised by a user will trigger the isCancelled callback. It would help if the user token was requested and passed with the callback or the React Native login will not be able to proceed

http://stackoverflow.com/questions/29358661/fbsdkloginmanager-loginwithpublishpermissions-always-returns-iscancelled-yes

**Comment by brentvatne** [comment]
@adrian-social-prod :+1: thanks for the heads up, oddly enough this seems to work for me still, I'll have to investigate further. If you have a chance to create a PR to fix this it would be appreciated too!

**Comment by adriansdev** [comment]
sorry, i hadn't used all the new code for keeping the state, i was following the blog post. when i use the full code then the token is returned
