### ISSUE TITLE
RCT_EXPORT deprecated

### ISSUE THREAD

**Issue by adriansdev** [brentvatne/react-native-login#7]
Just updated to the latest React Native build and a change to RCT_EXPORT has broken a couple of plugins including this

'Class FacebookLoginManager was not exported. Did you forget to use RCT_EXPORT_MODULE()?'

https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=RCT_EXPORT

Thanks

**Comment by brentvatne** [comment]
@adrian-social-prod - thanks! I just fixed this and pushed it, feel free to re-open the issue if it doesn't work for you :smile_cat:
