### ISSUE TITLE
Peer Dependencies issue

### ISSUE THREAD

**Issue by joshbedo** [brentvatne/react-native-login#8]
After running `npm install` this error was thrown.. I fixed it by upgrading `react-native` to `^4.0`

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_65558/AQf6P0aqlX3qfbT6fPcLWFU7S9rV3c/1.%2Btmux%2B%2528tmux%2529%2B2015-04-21%2B17-14-33.png?Expires=1429737359&Signature=SzzXvGCMNS~3CQGS4x4GB2UrQ6Gy2ZRYOAmfo8VXmgzFIIvuuPppsVMTjq9KSUmDaP0y2GzjXjXrLfuWZf2OhXPmjvjsAL~jrMMcBgPFVvwWiA~v1EgZOvV9SUXKoJ1qbMShCqYhdlWDg~xg3I4P6pZ8w4-Zgy1U1iNRUs4RKvwVUNO7sUjckZAe24El8I4CzYgUSV1ReTuNLzMxXNd8ealzT6XnK5w61oUg2xpu2ykfP91giow0MAh7TSxfXqMrNAJtf71kW-4GgRwXIBg7fzeM5M0nfZl0nQqCoMzVbOxfpc8lanSsl6CdIEAj6OExsFrH3~e0tHaItoQGvsZezQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by brentvatne** [comment]
Thanks @joshbedo - I forgot to update this, if you submit a PR I will merge right away :smile:

**Comment by joshbedo** [comment]
You got it

**Comment by brentvatne** [comment]
@joshbedo beat you to it! :P 0474eb9be0af80cec3496c755d92fe5559087648
